PROMPT='%F{blue}%1~%f $(git_prompt_info)%# '
RPROMPT='%F{244}%*%f'

ZSH_THEME_GIT_PROMPT_PREFIX='%F{yellow}git:'
ZSH_THEME_GIT_PROMPT_SUFFIX='%f '
ZSH_THEME_GIT_PROMPT_DIRTY='%F{red}*%f'
ZSH_THEME_GIT_PROMPT_CLEAN=''
